### ISSUE TITLE
support passing additional headers to posthog

### ISSUE THREAD

**Issue by brennan3** [nkezhaya/posthog#4]
There currently isn't a way to pass the client IP along on the `capture` calls. Using `x-forwarded-for` header would allow the event to reflect the client IP.

**Comment by nkezhaya** [comment]
Closed with #3 

Thanks for the PR!

**Comment by brennan3** [comment]
@nkezhaya I built a side project to help award open source maintainers by making it very easy for anyone to put $ awards on github issues. In theory, project maintainers could work on the issues and get the full reward, but in this case, my PR solved this issue. That said, the platform still awards the maintainer (you in this case) 10% of the bounty as you do the code review and merge the code. 

I had put $10 bounty on this issue - any chance you'd be willing to claim your share? (ha, only $1 in this case...)

It does require you to claim as USDC (crypto) on the arbitrum network. I'd be happy to send you a small amount of ETH so that you could claim your reward if you do not have any gas money. You should see your claimable bounty right on https://app.gitgig.io/rewards as you login with github on the app.

If you have any questions, jump in our telegram room and I can help you.  The project just launched, so it doesn't have any users yet, so I'm sprinkling a few $ on issues that relate to open source libraries that the project uses.  If you are not familiar with crypto and do not have a wallet, then no worries. I'm going to create a few bounties in crypto-native repos soon.
